project:
  type: website

website:
  title: "Rodrigo Sarlo"
  navbar:
    background: white
    foreground: dark
    search: true
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: research/index.qmd
        text: Research
        icon: book
      - href: about.qmd
        text: About
        icon: person-circle
    right:
      - icon: github
        href: https://github.com/rodrigosarloaf/personal_website
        aria-label: GitHub
        text: Source Code
  page-footer: 
    left: "&#169; 2025 Rodrigo Sarlo" 
    center: 
      - icon: envelope
        href: mailto:rodrigosarlofilho@gmail.com
      - text: "{{< iconify academicons:google-scholar >}}"
        href: https://scholar.google.com/citations?user=lGXEOr4AAAAJ
      - icon: linkedin
        href: https://www.linkedin.com/in/rodrigo-sarlo-antonio-filho-b93250144/
      - icon: github
        href: https://github.com/rodrigosarloaf
      - icon: instagram
        href: https://www.instagram.com/rodrigosarloaf
    right: "Made with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: true
